version: "3.9"

networks:
  app-net:
    driver: bridge

services:
  driver-service:
    build:
      context: .
      dockerfile: driver-service/Dockerfile
    container_name: driver-service
    ports:
      - "8081:8081"  # REST
      - "8386:8386"  # gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql
    networks:
      - app-net

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    depends_on:
      - driver-service
      - mssql
    networks:
      - app-net

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    restart: unless-stopped
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 12
